name: Run Braves Stats Scripts Daily

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run manually via GitHub Actions UI

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Or your required version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run braves_players_season_totals.py
      run: |
        python braves_players_season_totals.py

    - name: Commit and push CSV files
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin "https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git"
        git add *.csv
        if ! git diff --cached --quiet; then
          git commit -m "Daily stats update [skip ci]"
          echo "Pushing changes..."
          git push origin HEAD:main
        else
          echo "No changes to commit, skipping push."
        fi

          echo "No changes to commit, skipping push."
        fi

